apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-test-nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleet-test
  template:
    metadata:
      labels:
        app: fleet-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80